version: '3'

tasks:
  clean:
    desc: Clean the build directory
    cmds:
      - rm -rf {{.ROOT_DIR}}/build/*

  # CLI build tasks
  cli:
    desc: Build the CLI version of the app
    dir: cli
    requires:
      vars: [ os, arch ]
    vars:
      FILE: "{{if eq .os `windows`}}mediasim.exe{{else}}mediasim{{end}}"
      LDFLAGS: "{{if eq .os `windows`}}-ldflags=\"-linkmode=external -s -w -extldflags '-static -static-libgcc -static-libstdc++'\"{{end}}"
    env:
      CGO_ENABLED: 1
      GOOS: "{{.os}}"
      GOARCH: "{{.arch}}"
    cmds:
      - |
        go build {{.LDFLAGS}} -o "{{.ROOT_DIR}}/build/{{.FILE}}"
        {{if .isPackage}}7z a -tzip -mx=9 "{{.ROOT_DIR}}/build/mediasim_{{.os}}_{{.arch}}.zip" "{{.ROOT_DIR}}/build/{{.FILE}}"{{end}}

  package:
    desc: Build and pack in .zip files
    requires:
      vars: [ oses, archs ]
    cmds:
      - |
        for os in {{.oses}}; do
          for arch in {{.archs}}; do
            task cli os=$os arch=$arch isPackage=true
          done
        done