[package]
name = "cli"
version = "0.1.0"
edition = "2024"
description = "Calculate how similar images and videos are"

[[bin]]
name = "mediasim"
path = "src/main.rs"

[dependencies]
clap.workspace = true
csv.workspace = true
ctrlc.workspace = true
mediasim = { path = "../mediasim", features = ["cache", "serde"] }
ratatui.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
image.workspace = true
mediasim = { path = "../mediasim", features = ["test-support"] }
rust-sak.workspace = true
