// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * StartComparison loads media from a directory and groups them by similarity, emitting progress events.
 */
export function StartComparison(directory: string, includeImages: boolean, includeVideos: boolean, frameFlip: boolean, frameRotate: boolean, threshold: number): $CancellablePromise<void> {
    return $Call.ByID(4265235812, directory, includeImages, includeVideos, frameFlip, frameRotate, threshold);
}
