// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetThumbnail loads an image or extracts the first frame of a video, resizes it to fit within maxSize
 * pixels on the longest dimension, encodes it as JPEG, and returns the bytes along with the resulting
 * width and height.
 */
export function GetThumbnail(filePath: string, maxSize: number): $CancellablePromise<[string, number, number]> {
    return $Call.ByID(4155270388, filePath, maxSize).then(($result: any) => {
        $result[0] = $Create.ByteSlice($result[0]);
        return $result;
    });
}

/**
 * ListMedia returns all image and video file paths in the given directory (non-recursive).
 */
export function ListMedia(directory: string): $CancellablePromise<string[]> {
    return $Call.ByID(2016887960, directory).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
