// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetImage loads an image or extracts the first frame of a video, optionally resizes it to fit within
 * maxSize pixels on the longest dimension (0 means no resize), encodes it as JPEG, and returns the
 * bytes along with the original width and height.
 */
export function GetImage(filePath: string, maxSize: number): $CancellablePromise<[string, number, number]> {
    return $Call.ByID(1357871781, filePath, maxSize).then(($result: any) => {
        $result[0] = $Create.ByteSlice($result[0]);
        return $result;
    });
}

/**
 * ListMedia returns metadata for all image and video files in the given directory (non-recursive).
 */
export function ListMedia(directory: string): $CancellablePromise<$models.MediaInfo[]> {
    return $Call.ByID(2016887960, directory).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.MediaInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
