// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteFiles permanently removes the given file paths from disk.
 * It returns the list of paths that were successfully deleted.
 */
export function DeleteFiles(paths: string[]): $CancellablePromise<string[]> {
    return $Call.ByID(292600382, paths).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListMedia returns metadata for all image and video files in the given directory (non-recursive).
 */
export function ListMedia(directory: string): $CancellablePromise<$models.MediaInfo[]> {
    return $Call.ByID(2016887960, directory).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.MediaInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
