// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class MediaInfo {
    "path": string;
    "modTime": number;
    "fileSize": number;

    /** Creates a new MediaInfo instance. */
    constructor($$source: Partial<MediaInfo> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("modTime" in $$source)) {
            this["modTime"] = 0;
        }
        if (!("fileSize" in $$source)) {
            this["fileSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MediaInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): MediaInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MediaInfo($$parsedSource as Partial<MediaInfo>);
    }
}
