// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * PrepareDirectPlay stores the video path for direct serving and returns a URL the frontend can use.
 */
export function PrepareDirectPlay(videoPath: string): $CancellablePromise<string> {
    return $Call.ByID(52902379, videoPath);
}

/**
 * StartStream transcodes the video at videoPath into HLS segments and returns the middleware URL for the HLS manifest.
 * Uses a cache to skip transcoding if the video was already processed.
 */
export function StartStream(videoPath: string): $CancellablePromise<string> {
    return $Call.ByID(448723687, videoPath);
}

/**
 * StopStream cancels the active FFmpeg process without deleting cached segments.
 */
export function StopStream(): $CancellablePromise<void> {
    return $Call.ByID(390639501);
}
