// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetDimensions returns the original width and height of an image or video without fully decoding it.
 */
export function GetDimensions(filePath: string): $CancellablePromise<[number, number]> {
    return $Call.ByID(1360070473, filePath);
}
